
package:
  name: tnt
  version: 126

source:
  fn: master.zip
  url: https://github.com/chrisryancombs/TNT/archive/master.zip

about:
  home: http://math.nist.gov/tnt/
  license: public domain
  summary: collection of interfaces and reference implementations
    of numerical objects useful for scientific computing in C++.

extra:
  recipe-maintainers:
    - rbogle
