package:
  name: xalan-c
  version: 1.11

source:
  url: http://apache.cs.utah.edu//xalan/xalan-c/sources/xalan_c-1.11-src.tar.gz
  fn: xalan_c-1.11-src.tar.gz

requirements:
  build:
    - xerces-c>=3
  run:
    - xerces-c>=3
